server:
  port: 9001

grpc:
  server:
    port: 9091
  client:
    customer-service:
      address: discovery:///CUSTOMER-SERVICE
      negotiation-type: plaintext
  retry:
    max-attempts: 3
    base-delay-ms: 100
  timeout: 5s

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      observation-enabled: false

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  instance:
    metadata-map:
      grpcPort: 9091

jwt:
  private-key: ${JWT_PRIVATE_KEY}
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuyJa+tjYM5NCbMEOWERlyu6M/NN8Ix0gbya6gou1rVt7n5797eEkotoHkD6yWJPvDCHV4pQxzVnOu4vBH2Y3Nv7od7vgM89F8YbI83rJ5KSJ3VKFRnH12fs8g10hfY03jZ22cXw9EflidqHfa1hGN4Ddx8a9K0rQJEOIktqb7tiy8b6a6aWfHr1rluBTjfXnjiTsom+fH1HJOvg/QagH9g5elx9yJBkvx1bjIE4kC0tAUVbNecG8g7l+9QMn4mcnzTsz8CCxWo/5xLBxq34likLpa66thtuTMXtxlnFpvjioQdUVyNmQiCZdmEBtM/iJGEtBgM0Qa5DS7wWi4AsZTQIDAQAB
  key-id: "auth-service-v1"
  issuer: ${JWT_ISSUER}
  access-token-expiration: 3600
  refresh-token-expiration: 604800

security:
  otp:
    max-resend: 3
    cooldown-seconds: 30
    expires-in-seconds: 300
    session-expires-in-seconds: 1800
    max_attempts: 3
  reset-token:
    expires-in-seconds: 300
  login:
    max-attempts: 2
    lock-duration-minutes: 1
    max-attempts-permanent: 3

openapi:
  title: Auth Service API
  description: Authentication and authorization
  server-url: http://localhost:9000/api/auth
  server-description: Gateway - Local

outbox:
  scheduler:
    fixed-delay-ms: 5000
    retry-delay-seconds: 5