server:
  port: 9005

grpc:
  server:
    port: 9095
  client:
    order-service:
      address: discovery:///order-service
      negotiation-type: plaintext
  retry:
    max-attempts: 3
    base-delay-ms: 100
  timeout: 5s

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_service_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true
    listener:
      ack-mode: RECORD

kafka:
  consumer:
    dlt:
      suffix: ".DLT"
    retry:
      initial-interval-ms: 2000
      multiplier: 2.0
      max-kafka-retry: 3
      max-manual-retry: 3

eureka:
  instance:
    metadata-map:
      grpcPort: 9095

openapi:
  title: Payment Service API
  description: Payment Service API Documentation
  server-url: http://localhost:9000/api/payment
  server-description: Gateway - Local

vnp:
  tmn-code: REEW5TWL
  hash-secret: 6U1HOTU0MFE09R3CI22CJ9BIJT3KCU8M
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:3000/payment/result
  version: 2.1.0
  order-type: other
  locale: vn
  curr-code: VND
  refund-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  ipn-url: http://localhost:9000/api/payments/vnpay/ipn
  # This will NOT work because VNPay servers cannot access localhost
  # IPN requires a public accessible URL (e.g., ngrok or a real domain)
  # VNPay will call this endpoint server-to-server to update payment status

outbox:
  scheduler:
    fixed-delay-ms: 5000
    retry-delay-seconds: 5