server:
  port: 9010

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/search_service_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  elasticsearch:
    uris: http://localhost:9200

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: search-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true
    listener:
      ack-mode: RECORD

kafka:
  consumer:
    dlt:
      suffix: ".DLT"
    retry:
      initial-interval-ms: 2000
      multiplier: 2.0
      max-kafka-retry: 3
      max-manual-retry: 3

openapi:
  title: Search Service API
  description: Search Service API Documentation
  server-url: http://localhost:9000/api/search
  server-description: Gateway - Local

eureka:
  instance:
    metadata-map:
      grpcPort: 9100